#!/usr/bin/env node
/**
 * Generates src/lib/hijri-table.ts: the Umm al-Qura calendar from 1440 to 1500 AH as one character
 * per month (1 = 30 days, 0 = 29), read from Node's full ICU. The phone then converts dates without
 * depending on Hermes' Intl calendar support (DESIGN_PLAN §8). Run once; commit the result.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FIRST = 1440;
const LAST = 1500;
const DAY = 86_400_000;

const fmt = new Intl.DateTimeFormat('en-u-ca-islamic-umalqura-nu-latn', { year: 'numeric', month: 'numeric', day: 'numeric', timeZone: 'UTC' });
const hijri = (ms) => {
  const o = Object.fromEntries(fmt.formatToParts(new Date(ms)).map((p) => [p.type, p.value]));
  return { y: parseInt(o.year, 10), m: parseInt(o.month, 10), d: parseInt(o.day, 10) };
};

const starts = [];
for (let ms = Date.UTC(2018, 7, 1); ms < Date.UTC(2079, 0, 1); ms += DAY) {
  const h = hijri(ms);
  if (h.d === 1 && h.y >= FIRST && h.y <= LAST + 1) starts.push({ ...h, day: ms / DAY });
}
if (starts[0].y !== FIRST || starts[0].m !== 1) throw new Error('Table must start at 1 Muharram');
const lengths = [];
for (let i = 0; i + 1 < starts.length && starts[i].y <= LAST; i++) {
  const len = starts[i + 1].day - starts[i].day;
  if (len !== 29 && len !== 30) throw new Error(`Month ${starts[i].y}/${starts[i].m} has ${len} days`);
  lengths.push(len === 30 ? '1' : '0');
}
if (lengths.length !== (LAST - FIRST + 1) * 12) throw new Error(`Expected ${(LAST - FIRST + 1) * 12} months, got ${lengths.length}`);

const out = `// Generated by scripts/gen-hijri.mjs from Node's ICU (Umm al-Qura). Do not edit.
/** 1 Muharram ${FIRST}, as days since 1970-01-01. */
export const HIJRI_BASE_DAY = ${starts[0].day};
export const HIJRI_BASE_YEAR = ${FIRST};
/** One character per month from 1 Muharram ${FIRST} to Dhu al-Hijjah ${LAST}: 1 = 30 days, 0 = 29. */
export const HIJRI_LENGTHS =
  '${lengths.join('')}';
`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'hijri-table.ts'), out);
console.log(`hijri-table.ts: ${lengths.length} months, ${FIRST}–${LAST} AH`);
