// Generated by scripts/gen-sound-index.mjs. Do not edit.
export const SOUNDS = {
  bead: [require('../../assets/sounds/beads/bead-1.wav'), require('../../assets/sounds/beads/bead-2.wav'), require('../../assets/sounds/beads/bead-3.wav')] as number[],
  separator: [require('../../assets/sounds/beads/separator.wav')] as number[],
  imam: [require('../../assets/sounds/beads/imam.wav')] as number[],
  count: [require('../../assets/sounds/count/tap-1.wav'), require('../../assets/sounds/count/tap-2.wav')] as number[],
  ambient: {

  } as Record<string, number>,
};
